# Generated by Django 5.0.7 on 2024-08-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created', 'name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(on_delete=models.SET('Unknown Group'), to='base.group', unique=True),
        ),
    ]
