# Generated by Django 5.0.7 on 2024-08-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_course_options_alter_course_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(on_delete=models.SET('Unknown Group'), to='base.group'),
        ),
    ]
